/**:
  ros__parameters:
    robot_ip: "192.168.0.100"
    script_filename: ""
    output_recipe_filename: ""
    input_recipe_filename: ""
    tf_prefix: ""
    use_tool_communication: false
    tool_voltage: 0
    tool_parity: 0
    tool_baud_rate: 115200
    tool_stop_bits: 1
    tool_rx_idle_chars: 1.5
    tool_tx_idle_chars: 3.5
    servoj_gain: 300
    servoj_lookahead_time: 0.1
    use_fake_hardware: false
    fake_sensor_commands: false
    headless_mode: true