planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
response_adapters: >-
  default_planner_response_adapters/AddTimeOptimalParameterization
  default_planner_response_adapters/ValidateSolution
  default_planner_response_adapters/DisplayMotionPath

planner_configs:
  SBL:
    type: geometric::SBL
  RRT:
    type: geometric::RRT
  RRTConnect:
    type: geometric::RRTConnect
  RRTstar:
    type: geometric::RRTstar
  TRRT:
    type: geometric::TRRT
  PRM:
    type: geometric::PRM
  PRMstar:
    type: geometric::PRMstar

ur3e_manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - SBL
    - RRT
    - RRTConnect
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
  projection_evaluator: joints(shoulder_pan_joint,shoulder_lift_joint)
  longest_valid_segment_fraction: 0.005
