# Form implementation generated from reading ui file 'P5_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from user_interface.joystick import Joystick


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 645)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.videoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoLabel.sizePolicy().hasHeightForWidth())
        self.videoLabel.setSizePolicy(sizePolicy)
        self.videoLabel.setObjectName("videoLabel")
        self.verticalLayout_2.addWidget(self.videoLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Emergency_Stop = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Emergency_Stop.sizePolicy().hasHeightForWidth())
        self.Emergency_Stop.setSizePolicy(sizePolicy)
        self.Emergency_Stop.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: black;\n"
"    border-radius: 70px;     /* half of width/height */\n"
"    width: 140px;\n"
"    height: 140px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: pink;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkred;\n"
"}\n"
"")
        self.Emergency_Stop.setObjectName("Emergency_Stop")
        self.horizontalLayout_3.addWidget(self.Emergency_Stop)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Home_Position = QtWidgets.QPushButton(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_Position.sizePolicy().hasHeightForWidth())
        self.Home_Position.setSizePolicy(sizePolicy)
        self.Home_Position.setObjectName("Home_Position")
        self.horizontalLayout.addWidget(self.Home_Position)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Vision_State = QtWidgets.QPushButton(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Vision_State.sizePolicy().hasHeightForWidth())
        self.Vision_State.setSizePolicy(sizePolicy)
        self.Vision_State.setObjectName("Vision_State")
        self.horizontalLayout.addWidget(self.Vision_State)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.RUN_2 = QtWidgets.QPushButton(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.RUN_2.sizePolicy().hasHeightForWidth())
        self.RUN_2.setSizePolicy(sizePolicy)
        self.RUN_2.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}\n"
"")
        self.RUN_2.setObjectName("RUN_2")
        self.horizontalLayout.addWidget(self.RUN_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Switch_Camera_Type = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Switch_Camera_Type.sizePolicy().hasHeightForWidth())
        self.Switch_Camera_Type.setSizePolicy(sizePolicy)
        self.Switch_Camera_Type.setBaseSize(QtCore.QSize(0, 0))
        self.Switch_Camera_Type.setObjectName("Switch_Camera_Type")
        self.horizontalLayout_2.addWidget(self.Switch_Camera_Type)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Reset = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset.sizePolicy().hasHeightForWidth())
        self.Reset.setSizePolicy(sizePolicy)
        self.Reset.setObjectName("Reset")
        self.horizontalLayout_2.addWidget(self.Reset)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Undo = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Undo.sizePolicy().hasHeightForWidth())
        self.Undo.setSizePolicy(sizePolicy)
        self.Undo.setObjectName("Undo")
        self.horizontalLayout_2.addWidget(self.Undo)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.Eraser = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Eraser.sizePolicy().hasHeightForWidth())
        self.Eraser.setSizePolicy(sizePolicy)
        self.Eraser.setObjectName("Eraser")
        self.horizontalLayout_2.addWidget(self.Eraser)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Small_Pen = QtWidgets.QRadioButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Small_Pen.sizePolicy().hasHeightForWidth())
        self.Small_Pen.setSizePolicy(sizePolicy)
        self.Small_Pen.setObjectName("Small_Pen")
        self.verticalLayout.addWidget(self.Small_Pen)
        self.Medium_Pen = QtWidgets.QRadioButton(parent=self.tab_2)
        self.Medium_Pen.setObjectName("Medium_Pen")
        self.verticalLayout.addWidget(self.Medium_Pen)
        self.Large_Pen = QtWidgets.QRadioButton(parent=self.tab_2)
        self.Large_Pen.setObjectName("Large_Pen")
        self.verticalLayout.addWidget(self.Large_Pen)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.RUN_1 = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RUN_1.sizePolicy().hasHeightForWidth())
        self.RUN_1.setSizePolicy(sizePolicy)
        self.RUN_1.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}\n"
"")
        self.RUN_1.setObjectName("RUN_1")
        self.horizontalLayout_2.addWidget(self.RUN_1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(6, 1)
        self.horizontalLayout_2.setStretch(10, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sysinfoLabel = QtWidgets.QLabel(parent=self.tab_3)
        self.sysinfoLabel.setObjectName("sysinfoLabel")
        self.horizontalLayout_5.addWidget(self.sysinfoLabel)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Terminate = QtWidgets.QPushButton(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminate.sizePolicy().hasHeightForWidth())
        self.Terminate.setSizePolicy(sizePolicy)
        self.Terminate.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"QPushButton {\n"
"    background-color: orange;\n"
"    color: black;\n"
"}")
        self.Terminate.setObjectName("Terminate")
        self.verticalLayout_6.addWidget(self.Terminate)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Joystick = Joystick(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Joystick.sizePolicy().hasHeightForWidth())
        self.Joystick.setSizePolicy(sizePolicy)
        self.Joystick.setSizeIncrement(QtCore.QSize(2, 2))
        self.Joystick.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.Joystick.setObjectName("Joystick")
        self.verticalLayout_5.addWidget(self.Joystick)
        self.frame = QtWidgets.QFrame(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setSizeIncrement(QtCore.QSize(1, 1))
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_Z_down = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Z_down.sizePolicy().hasHeightForWidth())
        self.pushButton_Z_down.setSizePolicy(sizePolicy)
        self.pushButton_Z_down.setSizeIncrement(QtCore.QSize(0, 1))
        self.pushButton_Z_down.setObjectName("pushButton_Z_down")
        self.horizontalLayout_6.addWidget(self.pushButton_Z_down)
        self.pushButton_Z_up = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Z_up.sizePolicy().hasHeightForWidth())
        self.pushButton_Z_up.setSizePolicy(sizePolicy)
        self.pushButton_Z_up.setSizeIncrement(QtCore.QSize(0, 1))
        self.pushButton_Z_up.setObjectName("pushButton_Z_up")
        self.horizontalLayout_6.addWidget(self.pushButton_Z_up)
        self.verticalLayout_5.addWidget(self.frame)
        self.verticalLayout_5.setStretch(0, 4)
        self.verticalLayout_5.setStretch(1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoLabel.setText(_translate("MainWindow", "videoLabel"))
        self.Emergency_Stop.setText(_translate("MainWindow", "Emergency Stop"))
        self.Home_Position.setText(_translate("MainWindow", "Home Position"))
        self.Vision_State.setText(_translate("MainWindow", "Vision State"))
        self.RUN_2.setText(_translate("MainWindow", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Movement"))
        self.Switch_Camera_Type.setText(_translate("MainWindow", "Switch Camera Type"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.Undo.setText(_translate("MainWindow", "Undo"))
        self.Eraser.setText(_translate("MainWindow", "Eraser"))
        self.Small_Pen.setText(_translate("MainWindow", "Small"))
        self.Medium_Pen.setText(_translate("MainWindow", "Medium"))
        self.Large_Pen.setText(_translate("MainWindow", "Large"))
        self.RUN_1.setText(_translate("MainWindow", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Vision"))
        self.sysinfoLabel.setText(_translate("MainWindow", "sysinfoLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "System Information"))
        self.Terminate.setText(_translate("MainWindow", "Terminate"))
        self.pushButton_Z_down.setText(_translate("MainWindow", "-Z"))
        self.pushButton_Z_up.setText(_translate("MainWindow", "+Z"))
