# Form implementation generated from reading ui file 'P5_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from user_interface.joystick import Joystick


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1207, 694)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Emergency_Stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Emergency_Stop.setGeometry(QtCore.QRect(30, 480, 131, 121))
        self.Emergency_Stop.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: pink;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkred;\n"
"}\n"
"")
        self.Emergency_Stop.setObjectName("Emergency_Stop")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(180, 440, 811, 181))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 791, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Home_Position = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_Position.sizePolicy().hasHeightForWidth())
        self.Home_Position.setSizePolicy(sizePolicy)
        self.Home_Position.setObjectName("Home_Position")
        self.horizontalLayout.addWidget(self.Home_Position)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Vision_State = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Vision_State.sizePolicy().hasHeightForWidth())
        self.Vision_State.setSizePolicy(sizePolicy)
        self.Vision_State.setObjectName("Vision_State")
        self.horizontalLayout.addWidget(self.Vision_State)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.RUN_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.RUN_2.sizePolicy().hasHeightForWidth())
        self.RUN_2.setSizePolicy(sizePolicy)
        self.RUN_2.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}\n"
"")
        self.RUN_2.setObjectName("RUN_2")
        self.horizontalLayout.addWidget(self.RUN_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 791, 141))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Switch_Camera_Type = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Switch_Camera_Type.sizePolicy().hasHeightForWidth())
        self.Switch_Camera_Type.setSizePolicy(sizePolicy)
        self.Switch_Camera_Type.setBaseSize(QtCore.QSize(0, 0))
        self.Switch_Camera_Type.setObjectName("Switch_Camera_Type")
        self.horizontalLayout_2.addWidget(self.Switch_Camera_Type)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Reset = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset.sizePolicy().hasHeightForWidth())
        self.Reset.setSizePolicy(sizePolicy)
        self.Reset.setObjectName("Reset")
        self.horizontalLayout_2.addWidget(self.Reset)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Undo = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Undo.sizePolicy().hasHeightForWidth())
        self.Undo.setSizePolicy(sizePolicy)
        self.Undo.setObjectName("Undo")
        self.horizontalLayout_2.addWidget(self.Undo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.Eraser = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Eraser.sizePolicy().hasHeightForWidth())
        self.Eraser.setSizePolicy(sizePolicy)
        self.Eraser.setObjectName("Eraser")
        self.horizontalLayout_2.addWidget(self.Eraser)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Small_Pen = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Small_Pen.sizePolicy().hasHeightForWidth())
        self.Small_Pen.setSizePolicy(sizePolicy)
        self.Small_Pen.setObjectName("Small_Pen")
        self.verticalLayout.addWidget(self.Small_Pen)
        self.Medium_Pen = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.Medium_Pen.setObjectName("Medium_Pen")
        self.verticalLayout.addWidget(self.Medium_Pen)
        self.Large_Pen = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.Large_Pen.setObjectName("Large_Pen")
        self.verticalLayout.addWidget(self.Large_Pen)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.RUN_1 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RUN_1.sizePolicy().hasHeightForWidth())
        self.RUN_1.setSizePolicy(sizePolicy)
        self.RUN_1.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}\n"
"")
        self.RUN_1.setObjectName("RUN_1")
        self.horizontalLayout_2.addWidget(self.RUN_1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.sysinfoLabel = QtWidgets.QLabel(parent=self.tab_3)
        self.sysinfoLabel.setGeometry(QtCore.QRect(20, 10, 771, 131))
        self.sysinfoLabel.setObjectName("sysinfoLabel")
        self.tabWidget.addTab(self.tab_3, "")
        self.videoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(50, 40, 1111, 401))
        self.videoLabel.setObjectName("videoLabel")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(1000, 420, 201, 211))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Terminate = QtWidgets.QPushButton(parent=self.page)
        self.Terminate.setGeometry(QtCore.QRect(10, 10, 141, 111))
        self.Terminate.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"")
        self.Terminate.setObjectName("Terminate")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Joystick = Joystick(parent=self.page_2)
        self.Joystick.setGeometry(QtCore.QRect(20, 30, 161, 161))
        self.Joystick.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.Joystick.setMouseTracking(True)
        self.Joystick.setObjectName("Joystick")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Emergency_Stop.setText(_translate("MainWindow", "Emergency Stop"))
        self.Home_Position.setText(_translate("MainWindow", "Home Position"))
        self.Vision_State.setText(_translate("MainWindow", "Vision State"))
        self.RUN_2.setText(_translate("MainWindow", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Movement"))
        self.Switch_Camera_Type.setText(_translate("MainWindow", "Switch Camera Type"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.Undo.setText(_translate("MainWindow", "Undo"))
        self.Eraser.setText(_translate("MainWindow", "Eraser"))
        self.Small_Pen.setText(_translate("MainWindow", "Small"))
        self.Medium_Pen.setText(_translate("MainWindow", "Medium"))
        self.Large_Pen.setText(_translate("MainWindow", "Large"))
        self.RUN_1.setText(_translate("MainWindow", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Vision"))
        self.sysinfoLabel.setText(_translate("MainWindow", "sysinfoLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "System Information"))
        self.videoLabel.setText(_translate("MainWindow", "videoLabel"))
        self.Terminate.setText(_translate("MainWindow", "Terminate"))
